WEBXR_HAND_JOINT_NAMES = [
    "wrist",
    "thumb-metacarpal",
    "thumb-phalanx-proximal",
    "thumb-phalanx-distal",
    "thumb-tip",
    "index-finger-metacarpal",
    "index-finger-phalanx-proximal",
    "index-finger-phalanx-intermediate",
    "index-finger-phalanx-distal",
    "index-finger-tip",
    "middle-finger-metacarpal",
    "middle-finger-phalanx-proximal",
    "middle-finger-phalanx-intermediate",
    "middle-finger-phalanx-distal",
    "middle-finger-tip",
    "ring-finger-metacarpal",
    "ring-finger-phalanx-proximal",
    "ring-finger-phalanx-intermediate",
    "ring-finger-phalanx-distal",
    "ring-finger-tip",
    "pinky-finger-metacarpal",
    "pinky-finger-phalanx-proximal",
    "pinky-finger-phalanx-intermediate",
    "pinky-finger-phalanx-distal",
    "pinky-finger-tip",
]

MP21_NAMES = [
    "wrist",
    "thumb_cmc",
    "thumb_mcp",
    "thumb_ip",
    "thumb_tip",
    "index_mcp",
    "index_pip",
    "index_dip",
    "index_tip",
    "middle_mcp",
    "middle_pip",
    "middle_dip",
    "middle_tip",
    "ring_mcp",
    "ring_pip",
    "ring_dip",
    "ring_tip",
    "pinky_mcp",
    "pinky_pip",
    "pinky_dip",
    "pinky_tip",
]

DEFAULT_WEBXR_TO_MP21 = {
    "wrist": "wrist",
    "thumb_cmc": "thumb-metacarpal",
    "thumb_mcp": "thumb-phalanx-proximal",
    "thumb_ip": "thumb-phalanx-distal",
    "thumb_tip": "thumb-tip",
    "index_mcp": "index-finger-phalanx-proximal",
    "index_pip": "index-finger-phalanx-intermediate",
    "index_dip": "index-finger-phalanx-distal",
    "index_tip": "index-finger-tip",
    "middle_mcp": "middle-finger-phalanx-proximal",
    "middle_pip": "middle-finger-phalanx-intermediate",
    "middle_dip": "middle-finger-phalanx-distal",
    "middle_tip": "middle-finger-tip",
    "ring_mcp": "ring-finger-phalanx-proximal",
    "ring_pip": "ring-finger-phalanx-intermediate",
    "ring_dip": "ring-finger-phalanx-distal",
    "ring_tip": "ring-finger-tip",
    "pinky_mcp": "pinky-finger-phalanx-proximal",
    "pinky_pip": "pinky-finger-phalanx-intermediate",
    "pinky_dip": "pinky-finger-phalanx-distal",
    "pinky_tip": "pinky-finger-tip",
}

LEGACY_QUEST26_TO_WEBXR = {
    "thumb_metacarpal": "thumb-metacarpal",
    "thumb_proximal": "thumb-phalanx-proximal",
    "thumb_distal": "thumb-phalanx-distal",
    "thumb_tip": "thumb-tip",
    "index_metacarpal": "index-finger-metacarpal",
    "index_proximal": "index-finger-phalanx-proximal",
    "index_intermediate": "index-finger-phalanx-intermediate",
    "index_distal": "index-finger-phalanx-distal",
    "index_tip": "index-finger-tip",
    "middle_metacarpal": "middle-finger-metacarpal",
    "middle_proximal": "middle-finger-phalanx-proximal",
    "middle_intermediate": "middle-finger-phalanx-intermediate",
    "middle_distal": "middle-finger-phalanx-distal",
    "middle_tip": "middle-finger-tip",
    "ring_metacarpal": "ring-finger-metacarpal",
    "ring_proximal": "ring-finger-phalanx-proximal",
    "ring_intermediate": "ring-finger-phalanx-intermediate",
    "ring_distal": "ring-finger-phalanx-distal",
    "ring_tip": "ring-finger-tip",
    "pinky_metacarpal": "pinky-finger-metacarpal",
    "pinky_proximal": "pinky-finger-phalanx-proximal",
    "pinky_intermediate": "pinky-finger-phalanx-intermediate",
    "pinky_distal": "pinky-finger-phalanx-distal",
    "pinky_tip": "pinky-finger-tip",
}
